name: NPM Publish

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        registry-url: https://registry.npmjs.org/
    - name: Run a multi-line script
      run: |
        npm publish --access public,
        echo Successfully Published.
