name: NPM Publish

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        registry-url: https://registry.npmjs.org/
    - name: Publish to NPM
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        npm publish,
        echo Successfully Published.
